### ISSUE TITLE
fetch_bbs_data not working (again)

### ISSUE THREAD

**Issue by AdamCSmithCWS** [BrandonEdwards/bbsBayes#192]
After the recent fix for the `fetch_bbs_data` function, I'm getting this error:

```{r}
Type "yes" (without quotes) to agree: yes
Using data directory at C:\Users\adam_\AppData\Local/bbsBayes/bbsBayes
Connecting to USGS ScienceBase...Connected!
Downloading count data (Task 1/3)
[===================================================================================] 100% eta:  0s
Downloading route data (Task 2/3)
[===================================================================================] 100% eta:  0s
Downloading species data (Task 3/3)
[====================>--------------------------------------------------------------]  25% eta:  1sError in substring(x, first, last) : 
  invalid multibyte string at '<e0> ve'
```

This is with the most recent development version and the CRAN version. 

```{r}
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bbsBayes_2.5.1

loaded via a namespace (and not attached):
 [1] httr_1.4.3          rnaturalearth_0.1.0 pkgload_1.3.0       jsonlite_1.8.0      splines_4.2.0       geofacet_0.2.0     
 [7] shiny_1.7.1         assertthat_0.2.1    sp_1.5-0            progress_1.2.2      remotes_2.4.2       ggrepel_0.9.1      
[13] sessioninfo_1.2.2   pillar_1.8.0        lattice_0.20-45     glue_1.6.2          digest_0.6.29       promises_1.2.0.1   
[19] colorspace_2.0-3    Matrix_1.4-1        htmltools_0.5.2     httpuv_1.6.5        pkgconfig_2.0.3     devtools_2.4.4     
[25] purrr_0.3.4         xtable_1.8-4        scales_1.2.0        processx_3.5.3      rjags_4-13          jpeg_0.1-9         
[31] later_1.3.0         tibble_3.1.7        proxy_0.4-27        mgcv_1.8-40         generics_0.1.3      ggplot2_3.3.6      
[37] usethis_2.1.6       ellipsis_0.3.2      cachem_1.0.6        withr_2.5.0         cli_3.3.0           magrittr_2.0.3     
[43] crayon_1.5.1        mime_0.12           memoise_2.0.1       ps_1.7.0            fs_1.5.2            fansi_1.0.3        
[49] nlme_3.1-157        jagsUI_1.5.2        class_7.3-20        pkgbuild_1.3.1      profvis_0.3.7       tools_4.2.0        
[55] imguR_1.0.3         prettyunits_1.1.1   hms_1.1.1           lifecycle_1.0.1     stringr_1.4.0       munsell_0.5.0      
[61] geogrid_0.1.1       sbtools_1.1.19      callr_3.7.0         compiler_4.2.0      e1071_1.7-11        rlang_1.0.4        
[67] classInt_0.4-7      units_0.8-0         grid_4.2.0          rstudioapi_0.13     rappdirs_0.3.3      htmlwidgets_1.5.4  
[73] miniUI_0.1.1.1      gtable_0.3.0        DBI_1.1.3           curl_4.3.2          R6_2.5.1            gridExtra_2.3      
[79] dplyr_1.0.9         fastmap_1.1.0       rgeos_0.5-9         utf8_1.2.2          rprojroot_2.0.3     KernSmooth_2.23-20 
[85] stringi_1.7.6       parallel_4.2.0      Rcpp_1.0.8.3        vctrs_0.4.1         sf_1.0-8            png_0.1-7          
[91] coda_0.19-4         tidyselect_1.1.2    urlchecker_1.0.1   
```

**Comment by BrandonEdwards** [comment]
So this is interesting. I've merged your PR into a test branch so I could try it out on my system, and I now get the same error as before that was popping up in #191. 

I'm going to look into it a bit more and see if there is a way to set the file encoding based on the system's architecture. Will get back to you soon...

**Comment by AdamCSmithCWS** [comment]
It might be ugly, but what about a tryCatch() call within the function that would allow the fetch_bbs_data function to try the encoded version if the non-encoded version fails?

Here's one possible, clunky, but effective (at least on my system) approach:

```{r}

  species <- try(utils::read.fwf(temp, skip = lskip, strip.white = TRUE, header = FALSE,
                             colClasses = c("integer",
                                            "character",
                                            "character",
                                            "character",
                                            "character",
                                            "character",
                                            "character",
                                            "character",
                                            "character"),
                             widths = c(6, -1, 5, -1, 50, -1, 50, -1, 50, -1,
                                        50, -1, 50, -1, 50, -1, 50)))
  if(class(species) == "try-error"){
  species <- try(utils::read.fwf(temp, skip = lskip, strip.white = TRUE, header = FALSE,
                      colClasses = c("integer",
                                     "character",
                                     "character",
                                     "character",
                                     "character",
                                     "character",
                                     "character",
                                     "character",
                                     "character"),
                      widths = c(6, -1, 5, -1, 50, -1, 50, -1, 50, -1,
                                 50, -1, 50, -1, 50, -1, 50),
                      fileEncoding = "latin1"))
  }

```

**Comment by AdamCSmithCWS** [comment]
Wait! I'm not actually sure that this fileEncoding option is work. The french characters in the species file are not correctly imported. I wonder if it might be more stable to fix this by importing this one file manually then attaching a csv version of it to the package?

> It might be ugly, but what about a tryCatch() call within the function that would allow the fetch_bbs_data function to try the encoded version if the non-encoded version fails?
> 
> Here's one possible, clunky, but effective (at least on my system) approach:
> 
> ```
> 
>   species <- try(utils::read.fwf(temp, skip = lskip, strip.white = TRUE, header = FALSE,
>                              colClasses = c("integer",
>                                             "character",
>                                             "character",
>                                             "character",
>                                             "character",
>                                             "character",
>                                             "character",
>                                             "character",
>                                             "character"),
>                              widths = c(6, -1, 5, -1, 50, -1, 50, -1, 50, -1,
>                                         50, -1, 50, -1, 50, -1, 50)))
>   if(class(species) == "try-error"){
>   species <- try(utils::read.fwf(temp, skip = lskip, strip.white = TRUE, header = FALSE,
>                       colClasses = c("integer",
>                                      "character",
>                                      "character",
>                                      "character",
>                                      "character",
>                                      "character",
>                                      "character",
>                                      "character",
>                                      "character"),
>                       widths = c(6, -1, 5, -1, 50, -1, 50, -1, 50, -1,
>                                  50, -1, 50, -1, 50, -1, 50),
>                       fileEncoding = "latin1"))
>   }
> ```

**Comment by steffilazerte** [comment]
On my system (Ubuntu), adding `fileEncoding = "latin1"` correctly loads the data. @BrandonEdwards where did you run into the problem with the French characters not working?

```
Browse[1]> head(species)
  V1    V2                           V3                           V4                             V5
1  6 01770 Black-bellied Whistling-Duck    Dendrocygne à ventre noir         Dendrocygna autumnalis
2  7 01780       Fulvous Whistling-Duck            Dendrocygne fauve            Dendrocygna bicolor
```

**Comment by steffilazerte** [comment]
Also note that this is needed when loading routes too

**Comment by AdamCSmithCWS** [comment]
I don't totally understand what's going wrong. On my system, I get this kind of thing:
```{r}
bbs_data$species_strat[634:638,]
     seq   aou                              english                               french                 spanish         order        family
634 1300 05660 (White-winged Junco) Dark-eyed Junco     Junco ardoisé (à ailes blanches)   Junco hyemalis aikeni Passeriformes Passerellidae
635 1301 05690  (Gray-headed Junco) Dark-eyed Junco         Junco ardoisé (à tête grise) Junco hyemalis caniceps Passeriformes Passerellidae
636 1302 05677          Dark-eyed Junco (all forms) Junco ardois\xe9 (toutes les formes)          Junco hyemalis Passeriformes Passerellidae
637 1303 05700                    Yellow-eyed Junco                Junco aux yeux jaunes        Junco phaeonotus Passeriformes Passerellidae
638 1306 05540                White-crowned Sparrow            Bruant à couronne blanche  Zonotrichia leucophrys Passeriformes Passerellidae
```

**Comment by steffilazerte** [comment]
I suspect this is because you're looking at `species_strat` which is returned after `stratify()` which uses the lump species data frame which has issues and *also* needs to be loaded with `latin1` encoding 😅 . This is what I get after `stratify()` which I modified to use latin1 encoding: 
```
     seq   aou                              english                            french                 spanish         order        family       genus           species sp.bbs
634 1300 05660 (White-winged Junco) Dark-eyed Junco  Junco ardoisé (à ailes blanches)   Junco hyemalis aikeni Passeriformes Passerellidae       Junco   hyemalis aikeni   5660
635 1301 05690  (Gray-headed Junco) Dark-eyed Junco      Junco ardoisé (à tête grise) Junco hyemalis caniceps Passeriformes Passerellidae       Junco hyemalis caniceps   5690
636 1302 05677          Dark-eyed Junco (all forms) Junco ardoisé (toutes les formes)          Junco hyemalis Passeriformes Passerellidae       Junco          hyemalis   5677
637 1303 05700                    Yellow-eyed Junco             Junco aux yeux jaunes        Junco phaeonotus Passeriformes Passerellidae       Junco        phaeonotus   5700
638 1306 05540                White-crowned Sparrow         Bruant à couronne blanche  Zonotrichia leucophrys Passeriformes Passerellidae Zonotrichia        leucophrys   5540
```

**Comment by drhammed** [comment]
So, I am running into a similar problem as @AdamCSmithCWS  when running `"bbsBayes::fetch_bbs_data()"` on my Ubuntu system. Please note- the encoding is working well on my windows and Mac, but since it will run for hours/days, I would like to run the JAGS model on our server ( Ubuntu), and I can use other OS for other stuff. 
Thanks
 
Error message-  

> 1sError in substring(x, first, last) : 
>   invalid multibyte string at '<e0> vent<72>e noir                          Dendrocygna autumnalis                             Anseriformes                                       Anatidae                                           Dendrocygna                                        autumnalis                                
> 

**********************
*    Data Citation   *
**********************
Ziolkowski Jr., D.J., Lutmerding, M., Aponte, V.I., and Hudson, M-A.R., 2022, North American Breeding Bird Survey Dataset 1966 - 2021: U.S. Geological Survey data release, https://doi.org/10.5066/P97WAZE5

**********************
*    Terms of Use    *
**********************
Users of these BBS data are obligated to formally recognize their use of the program's data in publications, presentations and other outlets. Additionally, all work using these data should acknowledge the thousands of U.S. and Canadian participants who annually perform and coordinate the survey.

It is in the best interest for the continued success of the BBS that authors submit a reprint or pdf of their work featuring BBS data to the National BBS staff for inclusion in the program's bibliography. If a publication is based solely on the analysis of BBS data, we recommend that you involve National BBS staff with the writing and/or review of the manuscript.

Thank you for supporting the BBS program and we look forward to learning of your work.

*****************************
* Data Liability Disclaimer *
*****************************
This database, identified as the North American Breeding Bird Survey Dataset, has been approved for release and publication by the U.S. Geological Survey (USGS) and the Canadian Wildlife Service of Environment Canada (EC). Although this database has been subjected to rigorous review and is substantially complete, the USGS and EC reserve the right to revise the data pursuant to further analysis and review. Furthermore, it is released on the condition that the USGS, the U.S. Government, the EC, and the Canadian Government may not be held liable for any damages resulting from its authorized or unauthorized use.

It is also strongly recommended that careful attention be paid to the contents of the metadata files associated with the dataset. Information concerning the accuracy and appropriate uses of these data may be obtained from the metadata files, or from the National Program Managers.

By typing "yes", you signify that you have thoroughly reviewed the liability statement above and agree to the terms of use.
Type "yes" (without quotes) to agree: yes
Creating data directory at ~/.local/share/bbsBayes
Connecting to USGS ScienceBase...Connected!
Downloading count data (Task 1/3)
downloading file /tmp/RtmpOxbkvm/States.zip
  |==================================================================================| 100%
[===================================================================================] 100% eta:  0s
Downloading route data (Task 2/3)
downloading file /tmp/RtmpOxbkvm/Routes.zip
  |==================================================================================| 100%
[===========================>-------------------------------------------------------]  33% eta:  1sdownloading file /tmp/RtmpOxbkvm/Weather.zip
  |==================================================================================| 100%
[===================================================================================] 100% eta:  0s
Downloading species data (Task 3/3)
downloading file /tmp/RtmpOxbkvm/filea9a902c4ee090
[====================>--------------------------------------------------------------]  25% eta:  1sError in substring(x, first, last) : 
  invalid multibyte string at '<e0> vent<72>e noir                          Dendrocygna autumnalis                             Anseriformes                                       Anatidae                                           Dendrocygna                                        autumnalis                                        '

**Comment by steffilazerte** [comment]
Hi @drhammed, we're working on a fix, and as soon as we think we've got it, I'll let you know and perhaps you can test it out for us?

By the way, we're also working on a major overhaul of the package from JAGS to Stan. It probably won't be ready until sometime in the New Year, but just a heads up!

**Comment by drhammed** [comment]
Nice job, everyone. Thank you so much.
